<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE people [
    <!ELEMENT person (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT gender (#PCDATA)>
    <!ELEMENT tag (#PCDATA)>
]>
<people>
    <person>
        <name>Testy McTestFace</name>
        <email>mcTestFace@test.com</email>
        <phone>123-456-7890</phone>
        <age>56</age>
        <gender>m</gender>
        <tag>testTag</tag>
        <tag>testTag again</tag>
    </person>
    <person>
        <name>Testy McTestFace</name>
        <email>mcTestFace@test.com</email>
        <phone>123-456-7890</phone>
        <age>57</age>
        <gender>m</gender>
        <tag>testTag</tag>
    </person>
    <person>
        <name>Testy McTestFace2</name>
        <email>mcTestFace@test.com</email>
        <phone>123-456-7890</phone>
        <age>56</age>
        <gender>m</gender>
        <tag>testTag</tag>
    </person>
    <person>
        <name>Testy McTestFace3</name>
        <email>mcTestFace@test.com</email>
        <phone>123-456-7890</phone>
        <age>56</age>
        <gender>m</gender>
        <tag>testTag</tag>
    </person>
    <person>
        <name>Testy McTestFace4</name>
        <email>mcTestFace@test.com</email>
        <phone>123-456-7890</phone>
        <age>56</age>
        <gender>m</gender>
        <tag>testTag</tag>
    </person>
    <person>
        <name>Testy McTestFace5</name>
        <email>mcTestFace@test.com</email>
        <phone>123-456-7890</phone>
        <age>56</age>
        <gender>m</gender>
        <tag>testTag</tag>
    </person>
</people>